name: orcult_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.0
  - attrs=21.4.0
  - autopep8=1.6.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cairo=1.16.0
  - certifi=2022.12.7
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contourpy=1.0.7
  - curl=7.87.0
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.5.0
  - fiona=1.8.18
  - fontconfig=2.14.2
  - fonttools=4.39.0
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.1.4
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.21.1
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.18
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.2
  - importlib-metadata=4.8.3
  - importlib-resources=5.12.0
  - importlib_resources=5.12.0
  - jinja2=3.1.2
  - jpeg=9e
  - json-c=0.15
  - kealib=1.4.14
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.87.0
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgdal=3.1.4
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=13.5
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.9.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4
  - nspr=4.35
  - nss=3.88
  - numpy=1.24.2
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - packaging=23.0
  - pcre=8.45
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - poppler=21.03.0
  - poppler-data=0.4.12
  - postgresql=13.5
  - proj=8.0.1
  - pycodestyle=2.8.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pytest
  - pytest-cov
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - qt=5.12.9
  - rasterio=1.2.0
  - rasterstats=0.16.0
  - readline=8.2
  - setuptools=67.4.0
  - shapely=1.8.0
  - simplejson=3.17.6
  - six=1.16.0
  - smmap=5.0.0
  - snuggs=1.4.7
  - sqlite=3.40.1
  - tiledb=2.3.3
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - typing-extensions=4.0.1
  - typing_extensions=4.0.1
  - tzcode=2022g
  - tzdata=2022g
  - unicodedata2=15.0.0
  - wheel=0.38.4
  - xerces-c=3.2.3
  - xlwt=1.3.0
  - xz=5.2.10
  - zipp=3.6.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - asttokens==2.2.1
      - backcall==0.2.0
      - comm==0.1.3
      - debugpy==1.6.7
      - decorator==5.1.1
      - executing==1.2.0
      - geopandas==0.12.2
      - ipykernel==6.23.2
      - ipython==8.14.0
      - jedi==0.18.2
      - joblib==1.2.0
      - jupyter-client==8.2.0
      - jupyter-core==5.3.1
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.5.6
      - opencv-contrib-python==4.7.0.72
      - pandas==1.5.3
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.5.3
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.15.1
      - pylsd-nova==1.2.0
      - pyproj==3.4.1
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - pytz==2022.7.1
      - pyzmq==25.1.0
      - rtree==1.0.1
      - scikit-learn==1.2.1
      - scipy==1.10.1
      - stack-data==0.6.2
      - threadpoolctl==3.1.0
      - traitlets==5.9.0
      - wcwidth==0.2.6
