dependencies:
  - pip:
      - asttokens==2.2.1
      - backcall==0.2.0
      - comm==0.1.3
      - debugpy==1.6.7
      - decorator==5.1.1
      - executing==1.2.0
      - fiona==1.8.21
      - geopandas==0.12.2
      - ipykernel==6.23.2
      - ipython==8.14.0
      - jedi==0.18.2
      - joblib==1.2.0
      - jupyter-client==8.2.0
      - jupyter-core==5.3.1
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.5.6
      - opencv-contrib-python==4.7.0.72
      - pandas==1.5.3
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.5.3
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.15.1
      - pylsd-nova==1.2.0
      - pyproj==3.4.1
      - pyqt5-sip
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - pytz==2022.7.1
      - pyzmq==25.1.0
#      - "rasterio --no-binary rasterio"
      - rasterstats
      - rtree==1.0.1
      - scikit-learn==1.2.1
      - scipy==1.8
      - stack-data==0.6.2
      - threadpoolctl==3.1.0
      - traitlets==5.9.0
      - wcwidth==0.2.6
